// ═══════════════════════════════════════════════════════════════════
// DATA — LIBRARY & BLOCKS
// ═══════════════════════════════════════════════════════════════════
const LIBRARY={
  Quads:[
    {id:"lib_squat",name:"Squat",sets:4,repRange:[6,10],cues:"Full depth, knees track toes, brace hard",ms:"squat"},
    {id:"lib_hack_squat",name:"Hack Squat",sets:4,repRange:[8,12],cues:"Feet high on platform, full depth",ms:"hack-squat"},
    {id:"lib_leg_press",name:"Leg Press",sets:3,repRange:[10,15],cues:"Shoulder-width feet, don't lock out",ms:"leg-press"},
    {id:"lib_leg_press_n",name:"Leg Press (narrow)",sets:3,repRange:[10,15],cues:"Narrow feet, emphasises outer quad",ms:"leg-press"},
    {id:"lib_leg_ext",name:"Leg Extension",sets:3,repRange:[12,15],cues:"Full range, hard squeeze at top",ms:"leg-extension"},
    {id:"lib_split_squat",name:"Bulgarian Split Squat",sets:3,repRange:[8,12],cues:"Front foot forward, torso upright",ms:"bulgarian-split-squat"},
    {id:"lib_lunge",name:"Walking Lunge",sets:3,repRange:[10,14],cues:"Long stride, knee tracks over toes",ms:"walking-lunges"},
    {id:"lib_goblet_squat",name:"Goblet Squat",sets:3,repRange:[12,15],cues:"Elbows inside knees, chest tall",ms:"goblet-squat"},
    {id:"lib_step_up",name:"Step-Up",sets:3,repRange:[10,12],cues:"Drive through heel of front foot",ms:"step-ups"},
    {id:"lib_zercher_squat",name:"Zercher Squat",sets:4,repRange:[6,10],cues:"Bar in elbow crook, upright torso, full depth",ms:"zercher-squat"},
  ],
  Hamstrings:[
    {id:"lib_deadlift",name:"Deadlift",sets:4,repRange:[5,8],cues:"Lats tight, drive floor away",ms:"barbell-deadlift"},
    {id:"lib_rdl",name:"Romanian Deadlift",sets:3,repRange:[8,12],cues:"Push hips back, feel the stretch",ms:"romanian-deadlift"},
    {id:"lib_trap_dl",name:"Trap Bar Deadlift",sets:4,repRange:[6,10],cues:"Hips down to start, chest tall",ms:"trap-bar-deadlift"},
    {id:"lib_sumo_dl",name:"Sumo Deadlift",sets:4,repRange:[5,8],cues:"Wide stance, toes out, drive knees out",ms:"sumo-deadlift"},
    {id:"lib_leg_curl",name:"Lying Leg Curl",sets:3,repRange:[10,15],cues:"Full ROM, slow 3s eccentric",ms:"lying-leg-curl"},
    {id:"lib_seated_curl",name:"Seated Leg Curl",sets:3,repRange:[10,15],cues:"Full stretch, pause at peak",ms:"seated-leg-curl"},
    {id:"lib_nordic",name:"Nordic Curl",sets:3,repRange:[6,10],cues:"Slow eccentric, brace core",ms:"nordic-hamstring-curl"},
    {id:"lib_good_morning",name:"Good Morning",sets:3,repRange:[10,12],cues:"Soft knees, hinge at hips",ms:"good-mornings"},
  ],
  Glutes:[
    {id:"lib_hip_thrust",name:"Hip Thrust",sets:3,repRange:[10,15],cues:"Drive through heels, squeeze at top",ms:"barbell-hip-thrust"},
    {id:"lib_glute_bridge",name:"Barbell Glute Bridge",sets:3,repRange:[12,15],cues:"Feet flat, drive hips to ceiling",ms:"glute-bridge"},
    {id:"lib_cable_kickback",name:"Cable Kickback",sets:3,repRange:[12,15],cues:"Squeeze glute at top, control down",ms:"cable-glute-kickback"},
    {id:"lib_abduction",name:"Hip Abduction Machine",sets:3,repRange:[15,20],cues:"Full ROM, don't use momentum",ms:"hip-abduction"},
  ],
  Calves:[
    {id:"lib_standing_calf",name:"Standing Calf Raise",sets:4,repRange:[12,15],cues:"Full stretch at bottom, pause at top",ms:"standing-calf-raises"},
    {id:"lib_seated_calf",name:"Seated Calf Raise",sets:4,repRange:[12,15],cues:"Loaded stretch, pause at top",ms:"seated-calf-raise"},
    {id:"lib_leg_press_calf",name:"Leg Press Calf Raise",sets:3,repRange:[15,20],cues:"Toes on edge, full ROM",ms:"leg-press-calf-raise"},
  ],
  Chest:[
    {id:"lib_bench",name:"Bench Press",sets:4,repRange:[8,12],cues:"1s pause at chest, drive through heels",ms:"barbell-bench-press"},
    {id:"lib_incline_db",name:"Incline DB Press",sets:3,repRange:[10,15],cues:"Elbows 45°, feel upper chest stretch",ms:"incline-dumbbell-bench-press"},
    {id:"lib_db_bench",name:"DB Bench Press",sets:4,repRange:[8,12],cues:"Greater ROM than barbell, stretch at bottom",ms:"dumbbell-bench-press"},
    {id:"lib_cable_fly",name:"Cable Fly",sets:3,repRange:[12,15],cues:"Slight elbow bend, hard squeeze at center",ms:"cable-fly"},
    {id:"lib_pec_deck",name:"Pec Deck",sets:3,repRange:[12,15],cues:"Control the opening, squeeze at center",ms:"pec-deck-fly"},
    {id:"lib_db_pullover",name:"DB Pullover",sets:3,repRange:[12,15],cues:"Feel rib cage expand, lats and chest stretch",ms:"dumbbell-pullover"},
    {id:"lib_dips",name:"Dips (chest focus)",sets:3,repRange:[8,12],cues:"Lean forward, elbows flared slightly",ms:"chest-dips"},
    {id:"lib_pushup_weighted",name:"Weighted Push-Up",sets:3,repRange:[10,15],cues:"Weight plate on back, full ROM",ms:"push-ups"},
    {id:"lib_low_cable_fly",name:"Low-to-High Cable Fly",sets:3,repRange:[12,15],cues:"Pull upward arc, squeeze upper chest",ms:"cable-fly"},
  ],
  Back:[
    {id:"lib_cable_row",name:"Cable Row",sets:4,repRange:[8,12],cues:"Pull to lower chest, squeeze shoulder blades",ms:"seated-cable-rows"},
    {id:"lib_db_row",name:"DB Row",sets:4,repRange:[8,12],cues:"Elbow close to body, full stretch",ms:"one-arm-dumbbell-row"},
    {id:"lib_chest_row",name:"Chest-Supported Row",sets:4,repRange:[8,12],cues:"Chest on pad, pull elbows hard",ms:"chest-supported-row"},
    {id:"lib_lat_pull",name:"Lat Pulldown",sets:3,repRange:[10,15],cues:"Lean back slightly, pull to upper chest",ms:"lat-pulldown"},
    {id:"lib_pullup",name:"Pull-Up / Chin-Up",sets:3,repRange:[6,12],cues:"Dead hang start, chin over bar",ms:"pull-up"},
    {id:"lib_sa_cable_row",name:"Single-Arm Cable Row",sets:4,repRange:[8,12],cues:"Full rotation, stretch then row to hip",ms:"single-arm-cable-row"},
    {id:"lib_pullover_cable",name:"Cable Straight-Arm Pullover",sets:3,repRange:[12,15],cues:"Slight elbow bend, feel lats at top",ms:"straight-arm-pulldown"},
    {id:"lib_bb_row",name:"Barbell Row",sets:4,repRange:[6,10],cues:"Hinge 45°, pull to belly button",ms:"barbell-bent-over-row"},
    {id:"lib_tbar_row",name:"T-Bar Row",sets:4,repRange:[8,12],cues:"Neutral grip, chest tall, squeeze",ms:"t-bar-row"},
  ],
  Shoulders:[
    {id:"lib_ohp",name:"Overhead Press",sets:4,repRange:[6,10],cues:"Straight bar path, brace core",ms:"barbell-shoulder-press"},
    {id:"lib_db_ohp",name:"DB Shoulder Press",sets:4,repRange:[8,12],cues:"Neutral grip, full lockout",ms:"dumbbell-shoulder-press"},
    {id:"lib_lat_raise",name:"Lateral Raise",sets:3,repRange:[15,20],cues:"Lead with elbows, slight forward lean",ms:"dumbbell-lateral-raise"},
    {id:"lib_cable_raise",name:"Cable Lateral Raise",sets:3,repRange:[15,20],cues:"Elbow leads, don't shrug",ms:"cable-lateral-raise"},
    {id:"lib_face_pull",name:"Face Pull",sets:3,repRange:[15,20],cues:"Pull to forehead, external rotate",ms:"face-pull"},
    {id:"lib_rear_delt",name:"Rear Delt Fly",sets:3,repRange:[15,20],cues:"Lead with elbows, avoid traps",ms:"rear-delt-fly"},
    {id:"lib_upright_row",name:"Upright Row",sets:3,repRange:[10,15],cues:"Wide grip, elbows high, cable preferred",ms:"barbell-upright-row"},
    {id:"lib_arnold_press",name:"Arnold Press",sets:3,repRange:[10,12],cues:"Rotate palm out as you press",ms:"arnold-press"},
  ],
  Biceps:[
    {id:"lib_bb_curl",name:"Barbell Curl",sets:3,repRange:[10,15],cues:"No swinging, full ROM",ms:"barbell-curl"},
    {id:"lib_hammer",name:"Hammer Curl",sets:3,repRange:[10,15],cues:"Neutral grip, no swinging",ms:"hammer-curl"},
    {id:"lib_incline_curl",name:"Incline DB Curl",sets:3,repRange:[10,15],cues:"Arms behind torso for extra stretch",ms:"incline-dumbbell-curl"},
    {id:"lib_spider_curl",name:"Spider Curl",sets:3,repRange:[10,15],cues:"Chest on incline, elbows forward",ms:"spider-curl"},
    {id:"lib_cable_curl",name:"Cable Curl",sets:3,repRange:[12,15],cues:"Constant tension, squeeze at top",ms:"cable-curl"},
    {id:"lib_conc_curl",name:"Concentration Curl",sets:3,repRange:[12,15],cues:"Elbow on inner thigh, strict form",ms:"concentration-curls"},
    {id:"lib_reverse_curl",name:"Reverse Curl",sets:3,repRange:[10,15],cues:"Overhand grip, targets brachialis",ms:"reverse-curl"},
  ],
  Triceps:[
    {id:"lib_skull",name:"Skullcrusher",sets:3,repRange:[10,15],cues:"Upper arms vertical, full extension",ms:"skullcrusher"},
    {id:"lib_pushdown",name:"Cable Pushdown",sets:3,repRange:[12,15],cues:"Elbows locked at sides, full extension",ms:"cable-tricep-pushdown"},
    {id:"lib_overhead_tri",name:"Overhead Tricep Extension",sets:3,repRange:[10,15],cues:"Elbows forward, stretch at bottom",ms:"overhead-tricep-extension"},
    {id:"lib_dips_tri",name:"Tricep Dips",sets:3,repRange:[8,12],cues:"Upright torso, elbows close",ms:"tricep-dips"},
    {id:"lib_kickback",name:"DB Kickback",sets:3,repRange:[12,15],cues:"Upper arm parallel to floor, full extension",ms:"dumbbell-kickback"},
    {id:"lib_close_bench",name:"Close-Grip Bench Press",sets:3,repRange:[8,12],cues:"Hands shoulder-width, elbows tight",ms:"close-grip-bench-press"},
  ],
  Core:[
    {id:"lib_plank",name:"Plank",type:"time",sets:3,holdSec:30,cues:"Neutral spine, squeeze glutes and abs, breathe steadily",ms:"plank"},
    {id:"lib_side_plank",name:"Side Plank",type:"time",sets:3,holdSec:30,cues:"Stack or stagger feet, keep hips high and forward",ms:"side-plank"},
    {id:"lib_superman",name:"Superman Hold",type:"time",sets:3,holdSec:20,cues:"Lift arms and legs simultaneously, squeeze glutes at top",ms:"superman"},
    {id:"lib_hollow_body",name:"Hollow Body Hold",type:"time",sets:3,holdSec:20,cues:"Lower back pressed flat, arms and legs fully extended"},
    {id:"lib_dead_bug",name:"Dead Bug Hold",type:"time",sets:3,holdSec:30,cues:"Lower back flat against floor, breathe steadily throughout"},
    {id:"lib_wall_sit",name:"Wall Sit",type:"time",sets:3,holdSec:45,cues:"90° knee angle, back flat against wall, weight through heels",ms:"wall-sit"},
    {id:"lib_lsit",name:"L-Sit Hold",type:"time",sets:3,holdSec:15,cues:"Depress scapula, legs parallel to floor, point toes"},
    {id:"lib_copenhagen",name:"Copenhagen Plank",type:"time",sets:3,holdSec:20,cues:"Top leg on bench, keep hips high, body in straight line"},
    {id:"lib_roman_chair",name:"Roman Chair Crunch",sets:3,repRange:[15,20],cues:"Full ROM, control the descent, exhale at top",ms:"roman-chair-sit-up"},
    {id:"lib_mountain_climbers",name:"Mountain Climbers",type:"time",sets:3,holdSec:30,cues:"Hips level, drive knees fast, core tight",ms:"mountain-climbers"},
    {id:"lib_hanging_knee",name:"Hanging Knee Lift",sets:3,repRange:[12,15],cues:"Dead hang start, pull knees to chest, control down",ms:"hanging-leg-raise"},
    {id:"lib_jackknife",name:"Jackknife Sit-Up",sets:3,repRange:[12,15],cues:"Simultaneous leg and torso crunch, touch feet at top",ms:"jackknife-sit-up"},
  ],
};
